image: maven:3.6.3-jdk-8
stages:
  - build
  - test
  - deploy
build:
  stage: build
  script:
    - mvn clean package
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE

test_unit:
  stage: test
  script:
    - mvn test

test_integration:
  stage: test
  script:
    mvn integration-test
deploy:
  stage: deploy
  script:
    - kubectl create namespace machkour_elBrahimi
    - kubectl apply -f deployment.yml -n machkour_elBrahimi
    - kubectl apply -f service.yml -n machkour_elBrahimi
